# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Katas' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Katas

  target 'KatasTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'KatasUITests' do
    # Pods for testing
  end

end
