# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'Dojo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Katas

  target 'DojoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DojoUITests' do
    # Pods for testing
  end

end
